//UPDATED: Sep 2, 2024 @ 13:13
//Most quotes are pulled from the stoic. app (getstoic.com). so credit goes to them unless otherwise commented.

const affirmations = [
	"My success depends on my ability to sleep and rest.",
	"I see possibilities in every objective that I encounter.",
	"My mind is innovative and brilliant.",
	"Happiness is a choice.",
	"I am in control of my actions and responsible for them.", //This one is a Josh Maynard special :)
	'"Is a world without pain possible? Then don\'t ask the impossible."%0D%0A- Marcus Aurelius',
	"My gifts and talents are vast.",
	"I am grateful for my freedom.",
	"I am closer and closer to achieving my goals.",
	"I am grateful to be a part of this amazing universe.",
	"I embrace myself with love and kindness today.",
	"I am unyielding.",
	"I forgive myself for all the mistakes I have made",
	"I am overflowing with potential.",
	"Today, I greet this day, everyone and everything, with openness and acceptance as if I were encountering them for the first time.",
	"My existence is worthwhile.",
	"I am in complete charge of planning for my future.",
	"I deserve to be loved.",
	"I am worthy of true love.",
	"I am grateful to be myself.",
	"Today, I live in the present moment.",
	"Every part of me is enough.",
	"I choose to accept myself as myself.",
	"I choose to care for my body, not lessen it.",
	"I design my own life.",
	"I fill my day with hope and face it with joy.",
	"I choose to live life to the fullest.",
	"I find joy in developing myself continuously.",
	"Today, I tell the truth and speak honestly from the heart.",
	"I choose to make the most of every opportunity.",
	"I will continue to learn, grow, and improve.",
	"I am grateful to be alive.",
	"Today, I talk less and listen more.",
	"I am a unique, one-of-a-kind winner.",
	"I am a grateful for a new day to boss up.",
	"I invite obstacles into my life as practice rounds to greatness.",
	"I keep shining brightly in this world.",
	"Iam self-sufficient and grounded.",
	"I am proud of all the bad days I have survived.",
	"I value my mind, my authentic self, and the abilities given to me.",
];

export default affirmations;
